### ISSUE TITLE
TODO 📌

### ISSUE THREAD

**Issue by BlackChesire** [BlackChesire/Attendancy#2]
### Completed 🏁
- [x] Report attenance component - @BlackChesire 
- [x] Event management component - send emails to participants before and after the event - @BlackChesire
- [x] Other component icons implementation - update the navbar - @Avichai-Aziz 
- [x] Better UI/UX - make the same CSS for all pages - @Avichai-Aziz 
- [x] Add SignalR to update who attended - @BlackChesire 
- [x] change participant model add Nullable "IsArrived" - @BlackChesire 
- [x] implement a signup form - @BlackChesire 
- [x] creator can email link - @BlackChesire 
- [x] Report handling - fix the pop up for incoming participants who arrived - @BlackChesire 
- [x] Implement google maps API at the event-creation-form.ts - @BlackChesire
- [x] SMTP server (As a microservice) to allow mail sending - @Avichai-Aziz 
- [x] User management - create login and signup pages and connect them to database - @Avichai-Aziz 
- [x] Event creation screen - google maps intergated - @BlackChesire 
- [x] Create Traffic Controllers test using python - @BlackChesire 
- [x] authService should tell me who is the current user - @Avichai-Aziz 
- [x] Unique QR generator for each meet by guid - @BlackChesire 
- [x] Allow assigning of student to the event - @BlackChesire
